apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: budget-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:KodiKrishnan/budget-app-gitops.git
    targetRevision: HEAD
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: budget-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
