apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  application.instanceLabelKey: argocd.argoproj.io/instance
  exec.enabled: "true"
  timeout.reconciliation: "60s"
  users.anonymous.enabled: "false"
