apiVersion: v1
kind: Secret
metadata:
  name: repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
data:
  sshPrivateKey:LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEOHJWQkk0OGkvSXQrRjNaeUNHRnBKUUpnZWlZTDRWalY4Ni9wZkRrRE5SUUFBQUpEbnNoUXc1N0lVCk1BQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRDhyVkJJNDhpL0l0K0YzWnlDR0ZwSlFKZ2VpWUw0VmpWODYvcGZEa0ROUlEKQUFBRURUMnhYR3QxWWRVZDdrZzNNNEp1L1p0RThqN1BIYlJLK29jc0pwTDhHcSt2eXRVRWpqeUw4aTM0WGRuSUlZV2tsQQptQjZKZ3ZoV05YenIrbDhPUU0xRkFBQUFEV0Z5WjI5alpDMWhZMk5sYzNNPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K 
stringData:
  url: git@github.com:KodiKrishnan/budget-app-gitops.git
